import { useEffect, useState } from 'react'
import Head from 'next/head'
import Avatar from '../components/Avatar'
import AppLayout from '../components/AppLayout'
import Button from '../components/Button'
import Github from '../components/Github'
import { colors } from '../styles/theme'
import { loginWithGithub, isLogedIn, GithubSignOut } from '../firebase/client'

export default function Home () {
  const [user, setUser] = useState(undefined)

  useEffect(() => {
    isLogedIn(setUser)
  }, [])

  const handleClick = () => {
    loginWithGithub().then(res => {
      const { avatar, email, username } = res
      setUser({ avatar, email, username, name })
    }).catch(err => {
      console.log(err)
    })
  }

  const signOut = () => {
    GithubSignOut()
      .then(res => console.log(res))
  }

  return (
    <>
      <Head>
        <title>Twitter Dev</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <AppLayout>
        <h1>
          TwitterDev
        </h1>
        <p>Dev talk community</p>
        <p>Join us!</p>
        <div>
          {
            user === null &&
            <Button onClick={handleClick}>
              <Github
                width={28}
                height={28}
                fill={colors.white}
              />
              Login with GitHub
            </Button>
          }
          {
            user && user.avatar && (
              <div>
                <Avatar
                  src={user.avatar}
                  alt={user.name}
                  text={user.name}
                />
              </div>
            )
          }
          <button onClick={signOut}>Log out</button>
        </div>
      </AppLayout>

      <style jsx>{`
        h1 {
          color: #0070f3;
          margin: 0;
          line-height: 1.15;
          font-size: 3rem;
        }

        p {
          font-size: 20px;
          font-weight: bold;
          margin: 10px 0 0;
        }

        div {
          margin-top: 20px;
        }
      `}</style>
    </>
  )
}
