import { useEffect } from 'react'
import Head from 'next/head'

import Image from 'next/image'
import Button from 'components/Button'
import Github from 'components/Icons/Github'
import Logo from 'components/Icons/Logo'

import { colors } from '../styles/theme'
import { loginWithGithub } from '../firebase/client'

import spinner from '../public/spinner.gif'

import { useRouter } from 'next/router'
import useUser from 'hooks/useUser'

export default function Home () {
  const user = useUser()
  const router = useRouter()

  useEffect(() => {
    user && router.replace('/home')
  }, [user, router])

  const handleClick = () => {
    loginWithGithub()
      .catch(err => {
        console.log(err)
      })
  }

  return (
    <>
      <Head>
        <title>Twitter Dev</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Logo width={200} fill={colors.secondary} />
      <h1>
        TwitterDev
      </h1>
      <p>Dev talk community</p>
      <p>Join us!</p>
      <div>
        {
          user === null &&
          <Button onClick={handleClick}>
            <Github
              width={28}
              height={28}
              fill={colors.white}
            />
            Login with GitHub
          </Button>
        }
        {
          user === undefined && (
            <Image
              src={spinner}
              width={40}
              height={40}
              alt='Loading'
            />
          )
        }
      </div>

      <style jsx>{`
        h1 {
          color: #0070f3;
          margin: 0;
          line-height: 1.15;
          font-size: 3rem;
        }

        p {
          font-size: 20px;
          font-weight: bold;
          margin: 10px 0 0;
        }

        div {
          margin-top: 20px;
        }
      `}</style>
    </>
  )
}
